import "./styles/globals.scss";
import Header from "@/components/Header";
import {ModalProvider} from "@/contexts/ModalContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          <ModalProvider>
            <Header />
            {children}
          </ModalProvider>
      </body>
    </html>
  );
}
