FROM gradle:8.5-jdk21 AS builder
WORKDIR /app
COPY . .
RUN gradle clean bootJar -x test

FROM eclipse-temurin:21-jdk
WORKDIR /app
COPY --from=builder /app/build/libs /app/libs
RUN find /app/libs -name "*.jar" -exec cp {} /app/app.jar \;

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]

