TAG: 'APGCC_SHHA_INFER'
OUTPUT_DIR: './output/'
VIS: False

MODEL:
  ENCODER: 'vgg16_bn'
  ENCODER_kwargs: {"last_pool": False}
  DECODER: 'IFI'
  DECODER_kwargs:
    num_classes: 2
    inner_planes: 64
    feat_layers: [3, 4]
    pos_dim: 32
    ultra_pe: True
    learn_pe: False
    unfold: False
    local: True
    no_aspp: False
    require_grad: True
    out_type: 'Normal'
    head_layers: [1024, 512, 256, 256]

  STRIDE: 8
  ROW: 2
  LINE: 2
  POINT_LOSS_COEF: 0.0002
  EOS_COEF: 0.5

  AUX_EN: False  # 추론 시에는 보조 앵커 사용 안함
  AUX_NUMBER: [2, 2]
  AUX_RANGE: [2, 8]
  AUX_kwargs: {'pos_coef': 1., 'neg_coef': 1., 'pos_loc': 0.0002, 'neg_loc': 0.0002}

TEST:
  THRESHOLD: 0.5
  WEIGHT: './output/SHHA_best.pth'
