import SideNavigation from "@/components/SideNavigation";
import styles from "./layout.module.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <div className={styles.content}>
      <SideNavigation />
      {children}
    </div>
  );
}
