import Header from "@/components/Header";
import {ModalProvider} from "@/contexts/ModalContext";
import SideNavigation from "@/components/SideNavigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({children}) {
  return (
    <html lang="en">
      <body>
        <ModalProvider>
          <div>
            <SideNavigation/>
            {children}
          </div>
        </ModalProvider>
      </body>
    </html>
  );
}
